@startuml app
' hide fields
hide methods

package option {
    class CommandOptionKwargsBuilder<'a> {
    }
    class CommandOptionKwargs<'a> {
    }
    class CommandOptionBuilder<'a> {
    }
    class CommandOption<'a> {
    }
    enum CommandOptionType {
        Text
        File
        Int
        Float
    }

    CommandOptionKwargsBuilder --> CommandOptionKwargs : builds
    CommandOptionBuilder --> CommandOption : builds
    CommandOption --> CommandOptionKwargs : uses
    CommandOptionKwargs --> CommandOptionType : uses
}

package parser {
    interface Parser {
    }
}

package command {
    interface _Command<'a> {
    }
    interface Command<'a> {
    }

    class MockCommand<'a> {
    }
    class MainCommand<'a> {
    }

    Command --> _Command : extends
}

' Relationships between modules
MockCommand *-- CommandOption : contains
MainCommand *-- CommandOption : contains
Command --> Parser : extends
@enduml
