on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ inputs.cache-key }}-cargo-registry
        restore-keys: |
          ${{ inputs.cache-key }}-cargo-registry

    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ inputs.cache-key }}-cargo-index
        restore-keys: |
          ${{ inputs.cache-key }}-cargo-index

    - name: Build
      run: cargo build
