on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/build.yml
    with:
      cache-key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose

  build-artifact:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      cache-key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: target/release/